Feat/site backbone
torin-asakura/shinny-dvor pull request #3
Opened 2021-11-26 07:43 UTC by ikorol3107

ISSUES CLOSED: #2

2021-11-26 12:05 UTC, ikorol3107 commented
@TFK70 добавила index-page по аналогии с примером из таски, по идее все должно корректно работать, но страница не загружается. В package.json app зависимость `"@site/index-page": "workspace:site/index-page"` добавила. В tsconfig ничего не трогала. Каких загрузчиков ему не хватает?%-0
Ошибка:
```javascript
@ikorol3107 ➜ /workspaces/shinny-dvor (feat/site-backbone ✗) $ yarn workspace @site/app dev
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Using webpack 5. Reason: no next.config.js https://nextjs.org/docs/messages/webpack5
event - compiled successfully
wait  - compiling...
event - compiled successfully
wait  - compiling...
event - compiled successfully
Watchpack Error (initial scan): TypeError: Cannot destructure property 'withFileTypes' of '(intermediate value)(intermediate value)(intermediate value)' as it is null.
event - build page: /
wait  - compiling...
error - ../index-page/src/index.page.tsx
Module parse failed: Unexpected token (3:24)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| import React from 'react'
| 
> const IndexPage = () => <h1>Index page</h1>
| 
| export default IndexPage
event - build page: /next/dist/pages/_error
wait  - compiling...
error - ../index-page/src/index.page.tsx
```

2021-11-26 13:31 UTC, TFK70 commented
@ikorol3107 попробуй вынести next.config.js на уровень выше из `src`

2021-11-30 16:51 UTC, TFK70 requested changes

2021-11-30 16:51 UTC, TFK70 commented on site/app/src/pages/index.ts
> +import ServicesPage from '@site/services-page'
`export { default } from '@site/services-page'`

2021-11-30 16:51 UTC, TFK70 commented on site/header-fragment/src/header.component.tsx
> +            <Layout>
Елинственный контейнер внутри другого контейнера?

2021-12-01 16:25 UTC, TFK70 requested changes
Нет других страниц и все ссылки ведут на главную

2021-12-01 16:25 UTC, TFK70 commented on site/articles-fragment/src/all-articles/all-articles.component.tsx
> +                <Layout>
Контейнер в контейнере

2021-12-01 16:25 UTC, TFK70 commented on site/booking-page/src/booking.page.tsx
> +            <Logo />
Без контейнера

2021-12-01 16:25 UTC, TFK70 commented on site/footer-fragment/src/footer-component.tsx
> +                <Navigation />
Navigation в футере?
Во-первых это семантически нелогично, а во-вторых меню навигации в футере отличается от меню навигации в хедере

2021-12-01 16:25 UTC, TFK70 commented on site/footer-fragment/src/footer-component.tsx
> +            <Navigation />
Хуже навигейшна в футере только 2 навигейшна)

2021-12-01 16:25 UTC, TFK70 commented on site/header-fragment/src/header.component.tsx
> +          <Logo />
Без контейнера

2021-12-01 16:25 UTC, TFK70 commented on site/header-fragment/src/header.component.tsx
> +          <Navigation />
Теперь ясно в чем дело

Дело в том, что то, что у тебя является хедером - это и есть Navigation. Поэтому меня и сбило с толку его присутствие в футере

2021-12-01 16:25 UTC, TFK70 commented on site/navigation-fragment/src/navigation.component.tsx
> +      <NextLink href='/'>
Почему везде одинаковые пути? У тебя же должны отображаться другие страницы

2021-12-01 16:41 UTC, TorinAsakura commented on site/footer-fragment/src/footer-component.tsx
> +                <Navigation />
Navigation может быть в футере: семантика такое допускает, а вот тот факт, что они отличаются - это да

2021-12-01 19:00 UTC, ikorol3107 commented on site/footer-fragment/src/footer-component.tsx
> +                <Navigation />
> 

@TFK70 там отличие только в цвете шрифта и размере контейнера, в который помещается фрагмент navigation. Почему я не могу использовать его и в хэдере и в футере?

2021-12-01 19:08 UTC, TFK70 commented on site/footer-fragment/src/footer-component.tsx
> +                <Navigation />
@ikorol3107 нет, отличия не только в этом

1. Отличается логотип
2. Отличаются кнопки в конце навигейшена (в шапке это выбор диаметра и записаться, в футере это социалки)
3. Отличается выравнивание. В шапке оно по центру, в футере - по левому краю

В твоем случае Navigation в футере - это весь белый блок выше дивайдера

2021-12-01 19:09 UTC, TFK70 commented on site/footer-fragment/src/footer-component.tsx
> +                <Navigation />
@ikorol3107 есть еще один вариант: тебе не обязательно делать два разных навигейшена. Ты по-прежнему можешь использовать один, но менять его вид в зависимости от контекста, так как скелетон у обоих навигейшенов +- одинаковый, да и элементы есть общие

2021-12-02 08:53 UTC, ikorol3107 commented on site/footer-fragment/src/footer-component.tsx
> +                <Navigation />
@TFK70 ок, поняла . Просто у меня под navigation подразумевается только эта часть https://www.figma.com/file/vqze2qxVpYJDKtablQExoA/%D0%A8%D0%B8%D0%BD%D0%BD%D1%8B%D0%B9-%D0%B4%D0%B2%D0%BE%D1%80?node-id=320%3A377 , а весь блок целиком у меня называется хэдер. Navigation обязательно должен содержать в себе лого , социалки и прочее?

2021-12-02 10:32 UTC, TFK70 commented on site/footer-fragment/src/footer-component.tsx
> +                <Navigation />
Лого - точно должен, это тоже элемент навигации, а социалки находятся в том же блоке (получается и они идут в навигейшн)

2021-12-03 10:28 UTC, TFK70 requested changes

2021-12-03 10:28 UTC, TFK70 commented on site/articles-fragment/src/articles.component.tsx
> +  // FIXME change to LastArticles component
Опиши пожалуйста чуть подробнее что тут нужно сделать (имеется ввиду здесь, комментом, а не в коде)

2021-12-03 10:28 UTC, TFK70 commented on site/booking-page/src/booking.page.tsx
> +import { NextLink }       from '@ui/link'
Перемести его чуть выше, а то он в блоке с релятивными импортами

2021-12-03 10:28 UTC, TFK70 commented on site/booking-page/src/booking.page.tsx
> +          <Successed />
succeeded*

2021-12-03 10:28 UTC, TFK70 commented on site/booking-page/src/booking.page.tsx
> +          <Successed />
А еще лучше просто `Success`

2021-12-03 10:28 UTC, TFK70 commented on site/booking-page/src/booking/booking.component.tsx
> +  const isSended = () => {
isSended - это boolean

2021-12-03 10:28 UTC, TFK70 commented on site/booking-page/src/booking/booking.component.tsx
> +    return isSuccessful ? screenVar(SUCCESS) : screenVar(INVALID)
А у тебя это void

2021-12-03 10:28 UTC, TFK70 commented on site/booking-page/src/booking/booking.component.tsx
> +    const isSuccessful = false
Просто оставь эту переменную и повесь тудушку над ней

2021-12-03 10:28 UTC, TFK70 commented on site/index-page/src/index.page.tsx
> +    <Main />
Он должен называться Hero

2021-12-03 10:28 UTC, TFK70 commented on site/index-page/src/index.page.tsx
> +    <WorksExamples />
Не вижу здесь этого фрагмента - https://www.figma.com/file/vqze2qxVpYJDKtablQExoA/%D0%A8%D0%B8%D0%BD%D0%BD%D1%8B%D0%B9-%D0%B4%D0%B2%D0%BE%D1%80?node-id=315%3A189

Если он внутри WorksExamples - нужно вынести

2021-12-03 10:28 UTC, TFK70 commented on ui/condition/src/index.ts
> +const Condition = ({ match, children }) => match && children
Советую здесь писать `match ? children : null`

В твоем случае он возвращает undefined если !match, а реакт такое не любит. Если компонент ничего не возвращает - это null

2021-12-03 14:20 UTC, ikorol3107 commented on site/articles-fragment/src/articles.component.tsx
> +  // FIXME change to LastArticles component
@TFK70 сделать хэлпер который будет брать из списка allComponents только первые три элемента.  
А еще кстати есть вот такой элемент, который, как я поняла, отличается от LastArticles : https://www.figma.com/file/vqze2qxVpYJDKtablQExoA/%D0%A8%D0%B8%D0%BD%D0%BD%D1%8B%D0%B9-%D0%B4%D0%B2%D0%BE%D1%80?node-id=529%3A4734  . Это значит что у статьи должно быть свойство "theme" ?

2021-12-03 14:40 UTC, TFK70 commented on site/articles-fragment/src/articles.component.tsx
> +  // FIXME change to LastArticles component
@ikorol3107 
> сделать хэлпер который будет брать из списка allComponents только первые три элемента

// FIXME take first 3 elements

> А еще кстати есть вот такой элемент, который, как я поняла, отличается от LastArticles

А чем он отличается?

> Это значит что у статьи должно быть свойство "theme"

Не знаю, а что в theme будет лежать?

2021-12-03 15:15 UTC, ikorol3107 commented on site/articles-fragment/src/articles.component.tsx
> +  // FIXME change to LastArticles component
@TFK70 
- А чем он отличается?
последние 3 статьи например могут быть на разные темы: балансировка, хранение шин, сварка .., а "статьи для этой услуги" - это выборка статей по определенной теме, например статьи о балансировке. Я это так поняла.
-  Не знаю, а что в theme будет лежать?
ну можно и без theme обойтись, просто по названию услуги сортировать.

2021-12-03 15:21 UTC, TFK70 commented on site/articles-fragment/src/articles.component.tsx
> +  // FIXME change to LastArticles component
> последние 3 статьи например могут быть на разные темы: балансировка, хранение шин, сварка .., а "статьи для этой услуги" - это выборка статей по определенной теме, например статьи о балансировке. Я это так поняла.

Дай ссылки на дизайн пожалуйста, я сейчас по нему пробежался и вообще не понял о чем именно ты говоришь

> ну можно и без theme обойтись, просто по названию услуги сортировать.

Мне твоя идея понятнее не стала. Я даже не понимаю какую задачу ты этим хочешь решить

2021-12-03 15:27 UTC, ikorol3107 commented on site/articles-fragment/src/articles.component.tsx
> +  // FIXME change to LastArticles component
@TFK70 фрагмент "последние публикации": https://www.figma.com/file/vqze2qxVpYJDKtablQExoA/%D0%A8%D0%B8%D0%BD%D0%BD%D1%8B%D0%B9-%D0%B4%D0%B2%D0%BE%D1%80?node-id=529%3A4626
фрагмент "статьи для этой услуги": 
https://www.figma.com/file/vqze2qxVpYJDKtablQExoA/%D0%A8%D0%B8%D0%BD%D0%BD%D1%8B%D0%B9-%D0%B4%D0%B2%D0%BE%D1%80?node-id=529%3A4757

2021-12-03 15:29 UTC, TFK70 commented on site/articles-fragment/src/articles.component.tsx
> +  // FIXME change to LastArticles component
@ikorol3107 а тебе сейчас это зачем? Ты на этапе разметки контейнеров, зачем тебе знать какие там будут данные? Ты пока работаешь только с версткой, бизнес - потом

2021-12-03 15:47 UTC, TFK70 requested changes

2021-12-03 15:47 UTC, TFK70 commented on site/booking-page/src/booking/booking.component.tsx
> +  const getStatus = () => screenVar(SUCCESS)
getStatus, полагаю, возвращает статус
Можно пример такого статуса?

2021-12-03 16:12 UTC, ikorol3107 commented on site/booking-page/src/booking/booking.component.tsx
> +  const getStatus = () => screenVar(SUCCESS)
> 

@TFK70 функция, возвращает компонент в зависимости от статуса "успешно отправлено" или "ошибка". Как её назвать тогда?

2021-12-03 16:28 UTC, TFK70 commented on site/booking-page/src/booking/booking.component.tsx
> +  const getStatus = () => screenVar(SUCCESS)
@ikorol3107 это getStatus возвращает компонент?

getStatus возвращает то, что возвращает функция screenVar, и по твоей логие screenVar возвращает компонент

<details>
<summary>Спойлер</summary>
Это не так, можешь посмотреть в документации или прокликать самостоятельно что эта функция возвращает ничего, void, об этом я уже писал в реквестах выше
</details>

Начнем с того что я снова не понимаю какую задачу ты решаешь. Я не могу тебе никак помочь потому что абсолютно не понимаю что ты делаешь и какая у тебя проблема.

1. Напиши зачем тебе вообще этот getStatus нужен и что он должен возвращать
2. Напиши что делает screenVar и зачем он тебе нужен
3. Напиши где и как у тебя сейчас используется getStatus

2021-12-03 19:19 UTC, ikorol3107 commented on site/booking-page/src/booking/booking.component.tsx
> +  const getStatus = () => screenVar(SUCCESS)
@TFK70 
1. getStatus нужен чтоб понять отправлены данные клиента  или нет. Возвращать он должен функцию, которая присвоит нужное значение переменной screen. 
2.  screenVar  возвращает функцию, которая изменяет значение переменной screen, используемой как условие для Condition, чтоб отображать нужный компонент в зависимости от значения переменной:
```javascript
<Condition match={screen === INITIAL}>
          <Booking />
        </Condition>
        <Condition match={screen === SUCCESS}>
          <Success />
        </Condition>
        <Condition match={screen === INVALID}>
          <Invalid />
        </Condition>
```
3. после заполнения формы заявки пользователь кликает кнопку Записаться, где я и использую getStatus: 
`<Box width='100%' height={48} border='1px solid blue' onClick={() => getStatus()}>Button</Box>`

2021-12-03 19:21 UTC, TFK70 commented on site/booking-page/src/booking/booking.component.tsx
> +  const getStatus = () => screenVar(SUCCESS)
@ikorol3107 тогда это updateStatus, но вообще тебе этим тоже надо было заниматься на этапе работы с данными

2021-12-05 09:56 UTC, TFK70 approved these changes

2021-12-06 08:56 UTC, TorinAsakura commented on site/app/src/pages/_document.tsx
> +// import { withOpenGraph } from '@atls/next-document-with-opengraph'
зачем в пре оставлять закомменченные места?

2021-12-06 08:57 UTC, TorinAsakura commented on site/blog-page/package.json
> +  "name": "@site/blog-page",
полагаю, блог надо бы вынести наверх @TFK70

2021-12-06 09:12 UTC, TFK70 commented on site/blog-page/package.json
> +  "name": "@site/blog-page",
@TorinAsakura имеешь ввиду как отдельный сервис?

2021-12-06 09:45 UTC, TorinAsakura approved these changes

2021-12-06 09:45 UTC, merged