feat: apply styles
torin-asakura/shinny-dvor pull request #6
Opened 2021-12-07 20:07 UTC by ikorol3107

ISSUES CLOSED: #4

2021-12-08 15:46 UTC, TFK70 requested changes

2021-12-08 15:46 UTC, TFK70 commented on ui/scrollspy/package.json
> +  "name": "@ui/scrollspy",
К нему самостоятельно не приступай: составь задачу, как дело до него дойдет

2021-12-08 15:46 UTC, TFK70 commented on ui/card/package.json
> +  "name": "@ui/card",
Если с ним будут проблемы - аналогично, не пытайся их решить самостоятельно, сразу пиши коммент

2021-12-08 15:46 UTC, TFK70 commented on ui/button/src/styles/shape/abstract/normal-size.styles.ts
> +    fontFamily: 'IBM+Plex+Sans',
Почему не из темы?

2021-12-09 08:52 UTC, ikorol3107 commented on ui/button/src/styles/shape/abstract/normal-size.styles.ts
> +    fontFamily: 'IBM+Plex+Sans',
@TFK70 Не могу разобраться, почему у меня не берутся стили из темы , сделала коммит с текущим кодом ниже.

2021-12-09 11:07 UTC, TFK70 commented on ui/button/src/styles/shape/abstract/normal-size.styles.ts
> +    fontFamily: 'IBM+Plex+Sans',
@ikorol3107 где не берутся? как воспроизвести?

2021-12-09 11:46 UTC, ikorol3107 commented on ui/button/src/styles/shape/abstract/normal-size.styles.ts
> +    fontFamily: 'IBM+Plex+Sans',
@TFK70 
шаги для воспроизведения:
- заменить в ui/button/src/styles/shape/abstract/normal-size.styles.ts  `fontFamily: 'IBM+Plex+Sans'` 
на `fontFamily: theme.fonts.primary`

результат: TypeError: Cannot read properties of undefined (reading 'primary')

также не применяются стили у текста, например если я добавляю fontWeight  или fontSize к любому `<Text/>` в site : ошибки нет, но свойства текста не меняются.

2021-12-09 11:50 UTC, TFK70 commented on ui/button/src/styles/shape/abstract/normal-size.styles.ts
> +    fontFamily: 'IBM+Plex+Sans',
@ikorol3107 у тебя 2 приложения: в каком из них ошибка?

2021-12-09 11:53 UTC, ikorol3107 commented on ui/button/src/styles/shape/abstract/normal-size.styles.ts
> +    fontFamily: 'IBM+Plex+Sans',
> @ikorol3107 у тебя 2 приложения: в каком из них ошибка?

@TFK70 site

2021-12-09 12:17 UTC, TFK70 requested changes

2021-12-09 12:17 UTC, TFK70 commented on fragments/navigation-fragment/package.json
>      "@emotion/react": "^11.6.0",
Могу узнать что это?

2021-12-09 21:20 UTC, ikorol3107 commented
@TFK70 из-за чего может быть, что цвет текста из theme применяется к Text, а fontSize и fontWeight не применяется? Например вот тут: https://github.com/torin-asakura/shinny-dvor/blob/feat/apply-styles/site/booking-page/src/booking/booking.component.tsx#:~:text=%3CText%20fontSize%3D%27giant%27%20fontWeight%3D%27medium%27%3E и так в обоих приложениях. Уже голову сломала(.

2021-12-09 21:30 UTC, ikorol3107 commented
> > https://github.com/torin-asakura/shinny-dvor/blob/feat/apply-styles/site/booking-page/src/booking/booking.component.tsx#:~:text=%3CText%20fontSize%3D%27giant%27%20fontWeight%3D%27medium%27%3E
> 
> нету экспорта? https://github.com/torin-asakura/shinny-dvor/blob/feat/apply-styles/ui/theme/src/theme/index.ts

@TFK70 Спасибо!   _*пошла убиваться об стену..._

2021-12-11 08:58 UTC, TFK70 requested changes

2021-12-11 08:58 UTC, TFK70 commented on fragments/navigation-fragment/src/size-button/size-button.interface.ts
> +  pageStyle?: string
1. За что отвечает pageStyle?
2. Если у меня pageStyle='123qwe' - у меня все будет ок?

2021-12-11 08:58 UTC, TFK70 commented on ui/icons/replacements.ts
> +const getReplacement =
Скопируй сюда на всякий случай коммент с кратким мануалом по использованию из юсинка, проект-то другой, а хелпер по-прежнему сложный и не очевидный

2021-12-11 08:58 UTC, TFK70 commented on ui/icons/src/index.ts
> +/* eslint-disable */
Вообще-то у тебя папка src в которую билдятся иконки должна быть в гитигноре

2021-12-13 21:37 UTC, TFK70 requested changes

2021-12-13 21:37 UTC, TFK70 commented on fragments/footer-fragment/src/footer-component.tsx
> +import { SocialLinks } from '@fragments/social-links-fragment'
1. `fragments/social-links`, слово fragment добавляется только в конце названия директории
2. Это скорее ui

2021-12-13 21:37 UTC, TFK70 commented on fragments/navigation-fragment/src/navigation-item/navigation-item.interface.ts
> +  pageStyle?: string
А pageStyle это ...?

Я вроде уже писал про то, что это не просто string. Если я туда впишу 'werfwao4sejfo23w' твои типы меня пропустят, но приложение будет работать не так, как мне надо

И да, что это? Это светлая/темная тема?

2021-12-13 21:37 UTC, TFK70 commented on fragments/social-links-fragment/src/light-item/light-item.tsx
> +    <Button color='radius'>
Почему у тебя Dark и Light итемы абсолютно аналогичные, но при этом как разные компоненты?
У них же только цвет различается? И смена темной/светлой темы должна делаться совсем по-другому, с помощью...непосредственно темы.   В общем эту логику теперь ото всюду надо вычистить, я чуть позже дам инструкции

2021-12-13 21:37 UTC, TFK70 commented on fragments/social-links-fragment/src/social-links.component.tsx
> +const SocialLinks: FC<SocialLinksProps> = ({ pageStyle = 'light' }) => {
Если pageStyle действительно отвечает за светлую/темную тему - его вообще ото всюду нужно убрать

2021-12-13 21:37 UTC, TFK70 commented on fragments/social-links-fragment/src/social-links.component.tsx
> +const SocialLinks: FC<SocialLinksProps> = ({ pageStyle = 'light' }) => {
Ну и к слову, ты же вроде знаешь про контексты: зачем везде прокидывала это как проп руками?
Но теперь уже без разницы, все-равно вычищать

2021-12-13 21:37 UTC, TFK70 commented on fragments/social-links-fragment/src/social-links.component.tsx
> +  const [onVkHover, setOnVkHover] = useState(false)
Нуу...

С учетом того что SocialLinks уберется в ui я бы сделал так:

1. Сделал сущность SocialLink и отслеживал бы ховеры, клики и прочую грязь внутри него, а далее принял бы решение:

**Итемы сильно отличаются друг от друга (например итем vk от итема фейсбука)?**

**Да** - Либо делать отдельно по итему на каждую социалку (VkLink, FacebookLink и тд), либо все-равно делать один SocialLink, но насиловать его пропами снаружи, но в данном случае более предпочтителен первый вариант

**Нет** - Просто описываю общую логику для всех итемов в SocialLink и не парюсь

2. Внутри SocialLinks сделал бы как-то так:

```javascript
const SocialLinks = () => {
   return (
      <VkLink />
      <FacebookLink />
      ....
   )
}
```

Ну или аналогичное с SocialLink:

```javascript
<SocialLink social='vk' />
<SocialLink social='facebook' />
....
```

2021-12-13 21:37 UTC, TFK70 commented on site/booking-page/src/booking/booking.component.tsx
> +  const availableRadii = ['R12', 'R13', 'R14', 'R15', 'R16', 'R17', 'R18', 'R19', 'R20', 'R21']
Воу, повесь тудушку хоть что это с бека должно прилетать, а то выглядит так, будто так и задумано (и выглядит страшно)

2021-12-13 21:37 UTC, TFK70 commented on site/booking-page/src/booking/booking.component.tsx
> -          <Box width='100%' height={48} border='1px solid blue' onClick={() => updateStatus()}>
Так-так, и куда контейнер уходит? Мы же не должны трогать контейнеры на этапе раскраски

2021-12-13 21:37 UTC, TFK70 commented on site/booking-page/src/booking/booking.component.tsx
> -            Button
Button ты делаешь ровно там, где написано Button, а контейнер остается

2021-12-13 21:37 UTC, TFK70 commented on site/booking-page/src/invalid/invalid.component.tsx
> +        <Button color='secondary' onClick={() => screenVar(INITIAL)}>
Аналогично, кнопка теперь без контейнера, первого этапа будто и не было

2021-12-13 21:37 UTC, TFK70 commented on site/booking-page/src/success/success.component.tsx
>          <NextLink href='/'>
А здесь линк почему-то без контейнера

2021-12-13 21:37 UTC, TFK70 commented on ui/radio/src/radio.component.tsx
> +  <Container onClick={onClick} checked={checked}>
А почему не взяла из `@atls-ui-parts`?

2021-12-13 21:37 UTC, TFK70 commented on ui/radio/src/radio.component.tsx
> +  <Container onClick={onClick} checked={checked}>
И перед инициализацей любого ui компонента который сложнее текста или лейаута было бы неплохо синкаться со мной, чтобы дров не наломать (что уже произошло)

2021-12-13 21:37 UTC, TFK70 commented on ui/theme/src/theme/colors.ts
> +    choice: {
choice? Это как?

2021-12-14 21:30 UTC, TFK70 requested changes

2021-12-14 21:30 UTC, TFK70 commented on site/booking-page/src/booking/booking.component.tsx
> +      <Button onClick={() => updateStatus()}>Button</Button>
Куда все контейнеры постоянно пропадают? Все же было в порядке на первом этапе

2021-12-14 21:30 UTC, TFK70 commented on site/services-fragment/src/available-radii/available-radii.component.tsx
> +import { availableRadii } from '../../../data'
Что это? 0_o

2021-12-14 21:30 UTC, TFK70 commented on site/services-fragment/src/available-radii/available-radii.component.tsx
> +import { availableRadii } from '../../../data'
Что за data вообще? Какая у него зона ответственности?

2021-12-14 21:30 UTC, TFK70 commented on site/services-fragment/src/services.component.tsx
> +                    flexShrink={0}
Такие жирные вещи нужно выносить в отдельные сущности
Никому же не нужны файлы с версткой на 100+ строк?

2021-12-14 21:30 UTC, TFK70 commented on ui/radio/src/radio-list.component.tsx
> +        <Box width={width}>
Так...ты же видела мой коммент про радио?

2021-12-14 21:36 UTC, TFK70 requested changes

2021-12-14 21:36 UTC, TFK70 commented on site/services-infographics-fragment/src/services-infographics.component.tsx
> +      <InfoPoint top={[193, 259, 259]} left={[100, 129, 129]} />
Это абсолютное позиционирование элемента через пропсы с медиа-запросами? У тебя 1000% что-то не так, покажи это место в дизайне и напиши почему ты сделала именно так

2021-12-14 21:36 UTC, TFK70 commented on site/services-infographics-fragment/src/services-infographics.component.tsx
> +      <InfoPoint top={[193, 259, 259]} left={[100, 129, 129]} />
И да, снова нет контейнеров.....ни одного

2021-12-14 21:36 UTC, TFK70 commented on ui/info-point/src/outer-point/outer-point.component.ts
> +const OuterPoint = styled(Box)<OuterPointProps>(baseStyles, shapeStyles, appearanceStyles)
Покажи в дизайне на этот компонент

2021-12-14 21:53 UTC, TFK70 commented on site/booking-page/src/success/success.component.tsx
> +        {' '}
@ikorol3107 да, и Саша так ответил
Это не yarn format, а ваши пробелы `<Text> text </Text>` которые вы оставляли на этапе бекбона. Я думал вы знаете что делаете. До этого по крайней мере никто из вас так не делал, а тут прям как сговорились....

2021-12-14 21:56 UTC, TFK70 commented on site/services-infographics-fragment/src/services-infographics.component.tsx
> +      <InfoPoint top={[193, 259, 259]} left={[100, 129, 129]} />
@ikorol3107 к этому пока самостоятельно не приступай, такие нестандартные вещи всегда надо сначала проектировать и синкать, а только потом делать

2021-12-14 21:56 UTC, ikorol3107 commented on ui/info-point/src/outer-point/outer-point.component.ts
> +const OuterPoint = styled(Box)<OuterPointProps>(baseStyles, shapeStyles, appearanceStyles)
https://www.figma.com/file/vqze2qxVpYJDKtablQExoA/%D0%A8%D0%B8%D0%BD%D0%BD%D1%8B%D0%B9-%D0%B4%D0%B2%D0%BE%D1%80?node-id=468%3A1941

2021-12-14 21:57 UTC, TFK70 commented on ui/info-point/src/outer-point/outer-point.component.ts
> +const OuterPoint = styled(Box)<OuterPointProps>(baseStyles, shapeStyles, appearanceStyles)
[Аналогично](https://github.com/torin-asakura/shinny-dvor/pull/6#discussion_r769076694)

2021-12-14 21:58 UTC, ikorol3107 commented on site/services-fragment/src/available-radii/available-radii.component.tsx
> +import { availableRadii } from '../../../data'
@TFK70  вынесла в data/mocks.ts то, что будет приходить с сервера

2021-12-14 22:00 UTC, TFK70 commented on site/services-fragment/src/available-radii/available-radii.component.tsx
> +import { availableRadii } from '../../../data'
@ikorol3107 по этой части тоже чуть позже тогда разъясню ситуацию

Но если вкратце: все данные фетчатся децентрализованно, локально внутри фрагмента, а у тебя один большой датацентр к которому обращаются все фрагменты. Мы же на учебной репе с graphql так не делали

2021-12-18 16:52 UTC, TFK70 requested changes

2021-12-18 16:52 UTC, TFK70 commented on ui/card/src/card.component.tsx
> +          <Backdrop {...backdropProps} onClick={hide} />
Он тут нужен?

2021-12-18 16:52 UTC, TFK70 commented on ui/card/src/card.component.tsx
> +  const Container = styled(BaseContainer)(({ theme }) => ({
Ты уверена что понимаешь зачем он нужен? Он соответствует дизайну?

2021-12-18 16:52 UTC, TFK70 commented on ui/card/src/card.interface.ts
> +  notify?: boolean
notify это тоже один из вариантов карда, это было индивидуальное решение для юсинка
здесь  в этом есть необходимость?

2021-12-18 17:09 UTC, ikorol3107 commented on ui/card/src/card.component.tsx
> +          <Backdrop {...backdropProps} onClick={hide} />
@TFK70 да, он есть в дизайне

2021-12-18 17:13 UTC, ikorol3107 commented on ui/card/src/card.component.tsx
> +  const Container = styled(BaseContainer)(({ theme }) => ({
@TFK70 я ему задала стили согласно дизайну

2021-12-18 17:15 UTC, ikorol3107 commented on ui/card/src/card.interface.ts
> +  notify?: boolean
@TFK70  тут он не пригодится , согласна.

2021-12-20 13:01 UTC, ikorol3107 commented on ui/radio/src/radio.component.tsx
> +  <Container onClick={onClick} checked={checked}>
@TFK70 переделывать с @atls-ui-parts/checkbox ?

2021-12-20 13:58 UTC, ikorol3107 commented
@TFK70 вот этот фрагмент https://www.figma.com/file/vqze2qxVpYJDKtablQExoA/%D0%A8%D0%B8%D0%BD%D0%BD%D1%8B%D0%B9-%D0%B4%D0%B2%D0%BE%D1%80?node-id=347%3A572 появляется при нажатии на scrollspy или в какой момент он становится видимым?

2021-12-20 13:59 UTC, TFK70 commented
> https://www.figma.com/file/vqze2qxVpYJDKtablQExoA/%D0%A8%D0%B8%D0%BD%D0%BD%D1%8B%D0%B9-%D0%B4%D0%B2%D0%BE%D1%80?node-id=347%3A572

Задай вопрос в фигме

2021-12-20 14:43 UTC, ikorol3107 commented
@TFK70  список компонентов которые нужно сделать:

- scrollspy
- popover (для выбора радиуса)
- tooltip
- carousel 
- checkbox

инициализированы, но нуждаются в проверке:

- radio
- input

2021-12-21 10:44 UTC, TFK70 requested changes

2021-12-21 10:44 UTC, TFK70 commented on ui/radio/src/radio.component.tsx
> +  const [hover, setHover] = useState<boolean>(false)
Для этого же есть useHover из @ui/utils
Тебе понятно как с ним работать?

2021-12-21 10:44 UTC, TFK70 commented on ui/theme/src/theme/fonts.ts
> +  primary: 'IBM Plex Sans',
Теперь с ними все норм? Точно помощь не нужна?

2021-12-21 10:44 UTC, TFK70 commented on ui/radio/src/helper/getCheckColor.ts
> +}
```javascript
export const getCheckColor = (hover, checked) => {
   if (hover && !checked) return 'blue'
   if (checked) return 'white'
   return 'black'
}
```

И обязательно типизируй ее

2021-12-21 11:56 UTC, ikorol3107 commented on ui/theme/src/theme/fonts.ts
> +  primary: 'IBM Plex Sans',
@TFK70 да, теперь везде корректно отображаются шрифты

2021-12-21 15:31 UTC, ikorol3107 commented on ui/radio/src/radio.component.tsx
> +  const [hover, setHover] = useState<boolean>(false)
@TFK70 да, точно! Переделаю с ним. Как работать с ним понятно.

2021-12-21 17:10 UTC, ikorol3107 commented
@TFK70 вот это же toggle-buttons? - https://www.figma.com/file/vqze2qxVpYJDKtablQExoA/%D0%A8%D0%B8%D0%BD%D0%BD%D1%8B%D0%B9-%D0%B4%D0%B2%D0%BE%D1%80?node-id=574%3A9188
могу его делать начать?

2021-12-21 17:23 UTC, TFK70 commented
> https://www.figma.com/file/vqze2qxVpYJDKtablQExoA/%D0%A8%D0%B8%D0%BD%D0%BD%D1%8B%D0%B9-%D0%B4%D0%B2%D0%BE%D1%80?node-id=574%3A9188

Это switch, почему его в списке не было?

Можешь, вот пример из юсинка - https://github.com/YouThinkResearch/web/tree/master/frontend/ui/switch/src

2021-12-22 19:49 UTC, TFK70 requested changes
1. Что со страницей prices?
2. На странице blog у итемов остался желтый бордер
3. Здесь целых 2 проблемы: бордер у надписи Accordeon и криво стилизированный чекбокс (к тому же он не работает, так и должно быть?)

![image](https://user-images.githubusercontent.com/62806448/147147422-12daab30-1109-4e14-a6d0-bc3cc7e2d5c8.png)

2021-12-22 20:08 UTC, ikorol3107 commented
> криво стилизированный чекбокс
@TFK70  Я checkbox не делала пока ещё,  только radio.

2021-12-24 10:09 UTC, TFK70 requested changes
Что за синее поле?

![image](https://user-images.githubusercontent.com/62806448/147343565-ed262939-a3b3-4591-80cc-a48de08ee506.png)

2021-12-24 10:09 UTC, TFK70 commented on fragments/navigation-fragment/src/navigation-list/navigation-list.component.tsx
> +import { NavigationItem } from '../navigation-item/navigation-item.component'
что это?

2021-12-24 10:09 UTC, TFK70 commented on site/booking-page/src/success/success.component.tsx
> +        {' '}
@ikorol3107 ?

2021-12-24 10:12 UTC, TFK70 commented
@ikorol3107 этот блок тоже должен быть закончен, почему ты его так оставила?
![image](https://user-images.githubusercontent.com/62806448/147343817-a08a8c13-a016-413e-9b4f-e39b37a812df.png)

2021-12-24 10:53 UTC, ikorol3107 commented
@TFK70 Это же не tooltip? Как этот dropdown button назвать, я его в список забыла внести. https://www.figma.com/file/vqze2qxVpYJDKtablQExoA/%D0%A8%D0%B8%D0%BD%D0%BD%D1%8B%D0%B9-%D0%B4%D0%B2%D0%BE%D1%80?node-id=355%3A4864

2021-12-24 10:58 UTC, TFK70 commented
> @TFK70 Это же не tooltip? Как этот dropdown button назвать, я его в список забыла внести. https://www.figma.com/file/vqze2qxVpYJDKtablQExoA/%D0%A8%D0%B8%D0%BD%D0%BD%D1%8B%D0%B9-%D0%B4%D0%B2%D0%BE%D1%80?node-id=355%3A4864

Это Menu, появляется при нажатии на бургер. Если не нуждаешься в помощи - сначала спроектируй компонент: распиши сюда принцип его работы, сущности, на которые он делится и как будет выглядеть использование этого компонента в коде.

2021-12-24 11:13 UTC, ikorol3107 commented
@TFK70  Обновила список компонентов:

- [ ] Select
- [ ] Scrollspy
- [ ] Popover (для выбора радиуса)
- [ ] Tooltip
- [ ] Carousel
- [ ] Menu

2021-12-24 11:53 UTC, ikorol3107 commented
> > @TFK70 Это же не tooltip? Как этот dropdown button назвать, я его в список забыла внести. https://www.figma.com/file/vqze2qxVpYJDKtablQExoA/%D0%A8%D0%B8%D0%BD%D0%BD%D1%8B%D0%B9-%D0%B4%D0%B2%D0%BE%D1%80?node-id=355%3A4864
> 
> Это Menu, появляется при нажатии на бургер. Если не нуждаешься в помощи - сначала спроектируй компонент: распиши сюда принцип его работы, сущности, на которые он делится и как будет выглядеть использование этого компонента в коде.

Принцип работы: 
при нажатии на бургер открывается контейнер с NavigationList, появляется Backdrop. При этом Backdrop не должен распространяться на navigation-fragment. При нажатии на navigation-fragment, либо на Backdrop, контейнер с NavigationList закрывается. При нажатии на NavigationItem в контейнере выполняется переход на другую страницу и контейнер закрывается.

Сущности: 
- контейнер  с NavigationList
- Backdrop
- children (burger-button)

Как будет выглядеть в коде:
```javascript 
 <Layout display={['flex', 'none', 'none']}>
 <Menu 
   container={
   <Column >
    <NextLink href='/services'>
      <NavigationItem name='services' />
    </NextLink>
    <NextLink href='/contacts'>
      <NavigationItem name='contacts' />
    </NextLink>
    <NextLink href='/blog'>
      <NavigationItem name='blog' />
    </NextLink>
  </Box>
   }>
    <MenuIcon width={24} height={24} color='black' />
</Menu>
</Layout>
```

2021-12-24 13:06 UTC, TFK70 commented
@ikorol3107 из всех компонентов делай только селект, вот пример: https://github.com/YouThinkResearch/web/tree/master/frontend/ui/select/src

2021-12-25 13:45 UTC, ikorol3107 commented
> @ikorol3107 из всех компонентов делай только селект, вот пример: https://github.com/YouThinkResearch/web/tree/master/frontend/ui/select/src

@TFK70 сделала Select по аналогии примера,
при попытке подключить Select к проекту  страница не может сбилдится с ошибкой: 
`error - /workspaces/shinny-dvor/.yarn/__virtual__/framer-motion-virtual-5d664913f6/0/cache/framer-motion-npm-5.5.5-e5ac53d57d-95329fd69c.zip/node_modules/framer-motion/dist/es/components/AnimatePresence/index.mjs
Can't import the named export 'Children' from non EcmaScript module (only default export is available)
`

мой package.json для ui/select:
```javascript
{
  "name": "@ui/select",
  "version": "0.0.0",
  "license": "MIT",
  "main": "src/index.ts",
  "dependencies": {
    "@atls-ui-parts/button": "^0.0.4",
    "@atls-ui-parts/select": "^0.0.9",
    "@ui/checkbox": "workspace:ui/checkbox",
    "@ui/icons": "workspace:ui/icons",
    "@ui/input": "workspace:ui/input",
    "@ui/layout": "workspace:ui/layout",
    "@ui/text": "workspace:ui/text",
    "react-laag": "^2.0.3",
    "remove": "^0.1.5",
    "styled-system": "^5.1.5",
    "styled-tools": "^1.7.2"
  },
  "peerDependencies": {
    "@emotion/react": "*",
    "@emotion/styled": "*",
    "framer-motion": "*",
    "react": "*",
    "react-dom": "*"
  },
  "devDependencies": {
    "@emotion/css": "^11.7.1",
    "@emotion/react": "^11.4.1",
    "@emotion/styled": "^11.3.0",
    "framer-motion": "^5.5.5",
    "react": "^17.0.2",
    "react-dom": "16"
  }
}
```
как я понимаю, ошибка связана с framer-motion , но не понимаю  как ее можно исправить(

2021-12-25 17:33 UTC, TFK70 commented
@ikorol3107 а почему у тебя framer-motion в пирах?

2021-12-25 17:36 UTC, TFK70 commented
@ikorol3107 Еще не совсем понимаю почему у тебя там в зависимостях есть `@atls-ui/parts/button`, `@ui/checkbox`, `@ui/input` и `remove`

2021-12-25 17:51 UTC, ikorol3107 commented
> @ikorol3107 Еще не совсем понимаю почему у тебя там в зависимостях есть `@atls-ui/parts/button`, `@ui/checkbox`, `@ui/input` и `remove`

@TFK70 : button потому-что Select использует Button, стили для которой я беру из @atls-ui/parts/button. Чекбокс у меня там по дизайну есть: https://www.figma.com/file/vqze2qxVpYJDKtablQExoA/%D0%A8%D0%B8%D0%BD%D0%BD%D1%8B%D0%B9-%D0%B4%D0%B2%D0%BE%D1%80?node-id=347%3A1322 . Остальное убрала.  `framer-motion` перенесла из пиров в зависимости, ошибка сохранилась.

2022-07-06 18:11 UTC, TorinAsakura approved these changes

2022-07-06 18:11 UTC, merged